# NumPy (numerical python)
* A library for numerical computing in Python.
* Provides a fast & efficient tool for working with arrays, matrices, and mathematical operations like linear algebra & statistics.

In [ ]:
# soo fast (in memory)
import numpy as np 
import sys 
print(np.__version__)


2.3.3


In [5]:
my_list = [1,2,3,4]
my_list = my_list*2
print(my_list)

[1, 2, 3, 4, 1, 2, 3, 4]


In [6]:
array = np.array([1,2,ق3,4])
print(array)
print(type(array))

[1 2 3 4]
<class 'numpy.ndarray'>


In [7]:
array = array*2
print(array)

[2 4 6 8]


In [11]:

array = np.array('A')
print(array.ndim) # num of dimension

array = np.array(['A' , 'B' , 'C'])
print(array.ndim) # num of dimension

array = np.array([['A' , 'B' , 'C'],
                 ['D' , 'E' , 'F'],
                 ['G' , 'H' , 'I']])
print(array.ndim) # num of dimension

array = np.array([[['A' , 'B' , 'C'],['D' , 'E' , 'F'],['G' , 'H' , 'I']] ,
                 [['J' , 'K' , 'L'],['M' , 'N' , 'O'],['P' , 'Q' , 'R']],
                 [['S' , 'T' , 'U'],['V' , 'W' , 'X'],['Y' , 'Z' , ' ']]])
print(array.ndim) # num of dimension

0
1
2
3


In [12]:
print(array.shape) # layer Row Col

(3, 3, 3)


In [16]:
# access 
print(array[0][0][0])
print(array[0,0,0])

A
A


## indexing

In [29]:
array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])
print(array[0])
print(array[-1])
print(array[-3])

[1 2 3 4]
[13 14 15 16]
[5 6 7 8]


In [34]:
# start , end , step
print(array[0:3])
print('-----------------------------------------------------')

print(array[0:4:2])
print('-----------------------------------------------------')

print(array[::-1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-----------------------------------------------------
[[ 1  2  3  4]
 [ 9 10 11 12]]
-----------------------------------------------------
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [35]:
print(array[:,1])
print(array[:,1:4]) 

[ 2  6 10 14]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [37]:
print(array[1:3,1:3])
print(array[0:2,2:4])


[[ 6  7]
 [10 11]]
[[3 4]
 [7 8]]


## Math

In [17]:
# scaler arithmetic
array = np.array([1,2,3,4])
print(array + 1 )
print(array - 3 ) # for each element

[2 3 4 5]
[-2 -1  0  1]


In [42]:
# vectorized math func
array= np.array([4,9,16,20,30,90])
print(np.sqrt(array))
print(np.round(np.sqrt(array)))
print(np.pi)

[2.         3.         4.         4.47213595 5.47722558 9.48683298]
[2. 3. 4. 4. 5. 9.]
3.141592653589793


## Element-wise arithmetic

In [45]:
array1 = np.array([1,2,3,4])
array2 = np.array([5,6,7,8])

print(array1+array2)
print(array1-array2)
print(array1*array2)


[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]


## comparison operation

In [49]:
scores = np.array([1,22,33,44,55])
print( scores == 33)
print( scores >= 33)

scores[scores < 22] = 0
print(scores)

[False False  True False False]
[False False  True  True  True]
[ 0 22 33 44 55]


## Broadcasting

In [52]:
array1 = np.array([1,2,3,4])
array2 = np.array([[1],[2],[3],[4]])

print(array1*array2)

array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])
print(array*array2)


[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]
 [52 56 60 64]]


## aggregate functions

In [62]:
array = np.array([[1,2,3,4],
                  [5,6,7,8]])

print(np.sum(array))
print(np.mean(array))
print(np.std(array))
print(np.var(array))
print(np.min(array))
print(np.max(array))
print(np.argmin(array)) # position
print(np.argmax(array))

36
4.5
2.29128784747792
5.25
1
8
0
7


In [64]:
array = np.array([[1,2,3,4],
                  [5,6,7,8]])

print(np.sum(array , axis = 1))


[10 26]


## filtering

In [72]:
ages = np.array([[1,2,3,4 , 99 , 34,2  4, 33],
                  [5, 99,3, 4, 55, 23, 6,8]])

teenagers = ages[ages>18]
adults = ages[(ages <= 18) | (ages < 65)] 
seniors = ages[ages >= 65]

print(teenagers)
print(adults)
print(seniors)

[ 99  34 234  33  99  55  23]
[ 1  2  3  4 34 33  5  3  4 55 23  6  8]
[ 99 234  99]


In [76]:
adults = np.where(ages >= 18 , ages , 0) # replace by 0

print(adults)

[[  0   0   0   0  99  34 234  33]
 [  0  99   0   0  55  23   0   0]]


## Random


In [5]:
rng = np.random.default_rng(seed=1)

print(rng.integers(low = 1 , high=101 , size=(3,2)))

[[48 52]
 [76 96]
 [ 4 15]]


# Questions

In [ ]:
A20 = np.array(list(range(1, 31)))
print(A20)
A20 = A20.reshape(6, 5)
print(A20)
##########
part1 = A20[2:4, 0:2]
print("part1 =\n", part1)
part2 = A20[[0,1,2,3], [1,2,3,4]]
print("part2 = \n", part2)

part3 = A20[[0,4,5], 3:]
print("part3 =\n", part3)

all_selected = np.concatenate([part1.flatten(), part2.flatten(), part3.flatten()])
print("isin = \n" ,np.isin(A20, all_selected))
part4 = A20[~np.isin(A20, all_selected)]
print("part4 = \n", part4)



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
part1 =
 [[11 12]
 [16 17]]
part2 = 
 [ 2  8 14 20]
part3 =
 [[ 4  5]
 [24 25]
 [29 30]]
isin = 
 [[False  True False  True  True]
 [False False  True False False]
 [ True  True False  True False]
 [ True  True False False  True]
 [False False False  True  True]
 [False False False  True  True]]
part4 = 
 [ 1  3  6  7  9 10 13 15 18 19 21 22 23 26 27 28]
